apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 037561436790.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 037561436790.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: dbe7b0cb
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
